### ISSUE TITLE
AnkiMorphs V3 megathread

### ISSUE THREAD

**Issue by mortii** [mortii/anki-morphs#222]
There are some improvements to the current features and design that will break backwards compatibility, and they should be released at the same time:

- [x] alternative algorithm #191
- [x] settings design adjustments (#218)
- [x] improve `discard changes` message box
- [x] improve `new configs detected` message box
- [x]  Add option to disable keyboard shotcuts (#244) 
- [x] Toolbar
    - [x] Rename "U" and "A" in the toolbar -> "L" and "I" (lemma and inflection).
    - [x] Add options to hide either of those stats from the toolbar ^
    - [x] Add option to hide the recalc link
- [x] add new tag (#235)
- [x] Tags reset (#209)
    - [x] create background operation tag remover
    - [x] display warning dialog with option to reset tags when
        - [x] changing morphemizer
        - [x] changing field
        - [x] switching from lemma to inflection evaluation
            - [x] when switching same session
            - [x] when switching after saving 'lemma' option
- [x] don't trigger `tags reset` after discarding changes 
- [x] Future proof the config variable names by making them more abstract. Prefixing the tab name (e.g. `recalc_offset_new_cards`) makes them too rigid. Fixing this would cause a _very_ hard backwards compatibility break.
- [x] changes to extra fields (#221)(#195)
    - [x] add "all morphs" field
    - [x] add "all morphs count" field
    - [x] redo "unknown morphs" field
    - [x] redo "unknown morphs count" field
    - [x] rename `am-unknowns` -> `am-unknown-morphs`
    - [x] rename `am-unknowns-count` -> `am-unknown-morphs-count`
    - [x] add "am-study-morphs" (previously `am-unknowns`) https://github.com/mortii/anki-morphs/discussions/224#discussioncomment-9141216
    - [x] update `browse am-unknowns` -> `browse am-study-morphs`
- [x] card data
    - [x]  update only when state is 'new'
        - [x] due and tags
        - [x] am-all-morphs
        - [x] am-all-morphs-count
        - [x] am-study-morphs
        - [x] am-score
        - [x] am-score-terms
    - [x] update when state is 'review'
         - [x] potentially remove 'am-not-ready' 
         - [x] potentially remove 'am-ready' 
         - [x] potentially add 'am-fresh-morphs'
         - [x] potentially remove 'am-fresh-morphs'
    - [x] always update
        - [x] am-unknown-morphs
        - [x] am-unknown-morphs-count
        - [x] am-highlighted
- [x] always update both lemma and inflection learning intervals
- [x] check for lemma in `text_highlighting.py`
- [x] update known morphs reader
- [x] readability report uses learning interval based on user config
- [x] study plan builder:
    - [x] remove `morph-inflection` header from only lemma file
    - [x] remove `*-priority` columns
- [x] known morphs exporter
    - [x] optional inflection column
    - [x] optional occurrences column
    - [x] update headers
- [x] rework tests
    - [x] activate mypy
    - [x] give fake configs dynamic keys
    - [x] recalc
        - [x] lemma score == inflection score
        - [x] lemma known -> inflection known
        - [x] offset due
            - [x] lemma
            - [x] inflection
        - [x] known morphs
            - [x] successfully raised exception
            - [x] successfully read
                - [x] old known morphs format
                - [x] new known morphs format
        - [x] ignore names
        - [x] monolith collection
        - [x] default morph priority (#253)
    - [x] morph priority
        - [x] new frequency files format
            - [x] lemma and inflection columns
                - [x] evaluate on lemma
                - [x] evaluate on inflection
            - [x] only lemma column
                - [x] evaluate on lemma
        - [x] new study plan format
            - [x] minimal -> evaluate on lemma
            - [x] full -> evaluate on inflection
        - [x] raise exception when
            - [x] no headers
            - [x] minimal formats -> evaluating on inflection
            - [x] full study plan -> evaluating on lemma
        - [x] card collection priority
             - [x] evaluate on lemma
             - [x] evaluate on inflection
    - [X] review
    - [x] text highlighting
    - [x] readability report
        - [x] evaluate based on lemma
        - [x] evaluate based on inflection 
    - [x] generating known morphs file
        - [x] lemma + count
        - [x] lemma + inflection + count
    - [x] generating study plan 
        - [x] lemma only
        - [x] lemma + inflection
    - [x] add and integrate `pytest-cov`
- [x] remove `fields` from the `Cards` sql-table
- [x] bump anki version to 24.06.3 (78394314df3de943f8ab137018e1d17057418cbf)
- [x] anonymize arguments instead of deleting them
- [x] clean up `caching.py`
- [x] clean up `morph_priority_utils.py`
    - [x] make the error messages more specific
    - [x] splinter
- [x]  #227 
- [x] add config tests
- [x] misc algorithm tweaking
    - [x] weights
        - [x] add weights for all the terms
            - [x] $W_{\text{total}}^{\text{all}}$
            - [x] $W_{\text{total}}^{\text{unknown}}$
            - [x] $W_{\text{total}}^{\text{learning}}$
            - [x] $W_{\text{average}}^{\text{all}}$
            - [x] $W_{\text{average}}^{\text{learning}}$
            - [x] $W_{\text{target}}^{\text{all}}$
            - [x] $W_{\text{target}}^{\text{learning}}$
        - [x] increase the weight spinboxes max value to 999
        - [x] rename the weight configs to include the word 'weight'
        - [x] add a note about why there is no $W_{\text{average}}^{\text{unknown}}$
    - [x] coefficients
        - [x] make algorithm coefficients double spinboxes
        - [x] change the step size to '0.1'
        - [x] make the respective configs floats
        - [x] add a new algorithm test with floats
    - [x] targets
        - [x] rename 'target distance' -> 'target difference'
    - [x] change the default values
        - [x] learning morphs distance `a` coefficients -> 6 
        - [x] both target weights -> 10
        - [x] update test collections
- [x] add [dependabot ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore)
    - [x] PyQt6
    - [x] PyQt6-Qt6
    - [x] PyQt6-WebEngine
    - [x] PyQt6-WebEngine-Qt6
    - [x] PyQt6_sip
    - [x] numpy
- [x] update code comments in `card_score.py`
- [x] update shortcuts
    - [x] recalc
    - [x] settings
    - [x] progression
- [x] update min size of settings window
- [x] update termonology: `frequency file` -> `priority file` 
    - [x] change directory name in anki profile
    - [x] replace in the guide
    - [x] change `frequency file generator`
        - [x] rename
        - [x] change default name of output file
    - [x] update tests
- [x] tweak progression window layout
- [x] update guide
    - [x] algorithm explanation
    - [x] settings
        - [x] index
        - [x] general tab
        - [x] note filters
        - [x] extra fields
            - [x] am-all-morphs
            - [x] am-all-morphs-count
            - [x] am-score
            - [x] am-score-terms
            - [x] am-unknowns -> am-unknown-morphs
            - [x] am-unknowns-count -> am-unknown-morphs-count
            - [x] am-study-morphs
            - [x] update card template with am-study-morphs
        - [x] tags
        - [x] preprocess
        - [x] card handling
        - [x] algorithm
        - [x] toolbar
        - [x] shortcuts
        - [x] remove recalc tab
    - [x] changes to anki
    - [x] prioritizing
        - [x] frequency files have an increased max size
        - [x] generate new frequency files
            - [x] Cantonese
            - [x] Catalan
            - [x] Chinese
            - [x] Croatian
            - [x] Danish
            - [x] Dutch
            - [x] English
            - [x] Finnish
            - [x] French
            - [x] German
            - [x] Greek (Modern)
            - [x] Italian
            - [x] Japanese
                - [x] anime
                - [x] news
            - [x] Korean
            - [x] Lithuanian
            - [x] Macedonian
            - [x] Norwegian
            - [x] Polish
            - [x] Portuguese
            - [x] Romanian
            - [x] Russian
            - [x] Slovenian
            - [x] Spanish
            - [x] Swedish
            - [x] Ukrainian
    - [x] known morphs
    - [x] generators
    - [x] tweak progression window guide
    - [x] reset tags
- [x] manual testing on anki 24.06.3
    - [x] macos
        - [x] install from update
            - [x] new configs detected
        - [x] pop-up windows
            - [x] settings
            - [x] reset tags
            - [x] progression
            - [x] generators 
            - [x] recalc error: note filter guide
            - [x] invalid priority file
    - [x] windows 11 
        - [x] install from update
            - [x] new configs detected
        - [x] pop-up windows
            - [x] settings
            - [x] reset tags
            - [x] progression
            - [x] generators
            - [x] recalc error: note filter guide
            - [x] invalid priority file
- [x] update version string
- [x] remove all print statements
- [x] update contributors
- [x] rebase/squash and merge
- [x] add arabic diacritical marks to space morphemizer (#250)
- [x] release updated card collection

**Comment by mortii** [comment]
This issue is mostly a placeholder/tracker for the roadmap. Any feedback/questions/discussions can be had here:  #224, or in any of the relevant discussions/issues linked above.

**Comment by mortii** [comment]
> Okay, I have a (very badly coded) test version that has implemented the new algorithm and an option to choose between lemma priority and inflection priority!
>
>This version can be found in the latest [algorithm](https://github.com/mortii/anki-morphs/tree/algorithm) branch, or you can download it from google drive (github doesn't like .addon files): [ankimorphs-v3-0-0-testing-1](https://drive.google.com/file/d/1jMrVYax4aAXOTDYxMT1NMzXIuXL-_Mp_/view?usp=sharing)
>
>The algorithm "morph targets" stuff looks complicated, but all you do is define a range with no punishment, and then either side of that range you can specify a punishment curve (ax^2+bx+c), the default is this:
>
>![Screenshot from 2024-05-18 11-49-09](https://github.com/mortii/anki-morphs/assets/15674619/913466c4-1057-4a15-9499-e7516f738e52)
>
>([graph link](https://www.geogebra.org/graphing/ta3eqb8y))
>
>Any and all feedback would be very much appreciated!

_Originally posted by @mortii in https://github.com/mortii/anki-morphs/discussions/191#discussioncomment-9477791_

**Comment by mortii** [comment]
New testing build: [3.0.0-testing-2](https://drive.google.com/file/d/1T_R29DCCAJiWCipZWCETSJtRu755N5u1/view?usp=sharing) (google drive)

### Changelog
- "lower morph targets" settings are now capped to always be lower than the "upper morph targets"

**Comment by mortii** [comment]
New testing build: [3.0.0-testing-3](https://drive.google.com/file/d/1GqfHMFZE-L2YklJkeEz4f3Rr5n7CNFA7/view?usp=sharing) (google drive)

### Changelog
- if "Morph Prioirity: Lemma" is selected:
    - cards can now be skipped on review if the morphs lemmas are already known
    - all inflections are set to known during recalc if their lemma is known

In future versions the "Morph Prioirity: Lemma" option will be renamed, and it will be moved to a new "General" tab in the settings.

**Comment by mortii** [comment]
v3 released: https://github.com/mortii/anki-morphs/releases/tag/v3.0.0
